#!/bin/bash

THISMETHOD="matrixeqtl"
THISJOBDEPS=""
EXTRAFLAGS=""
if [ "${SHUFFLE}" = "true" ]; then
    THISMETHOD="matrixeqtl_rand"
    EXTRAFLAGS="--randomize"
    SHUFFLE=false
fi

JOBSUBDIR_MATRIX_EQTL="${JOBSUBDIR_DATA}/${THISMETHOD}"

for CHRM in ${CHRNUMS}; do
    SPECIFIC_JOBSUBDIR="${JOBSUBDIR_MATRIX_EQTL}/chr${CHRM}"
    if [ -d ${SPECIFIC_JOBSUBDIR} ]; then rm -rf ${SPECIFIC_JOBSUBDIR}; fi; mkdir -p ${SPECIFIC_JOBSUBDIR}

    SPECIFIC_OUTDIR="${OUTDIR_DATA}/${THISMETHOD}/chr${CHRM}"
    if [ ! -d ${SPECIFIC_OUTDIR} ]; then mkdir -p ${SPECIFIC_OUTDIR}; fi
    OUTFILE_CIS="${SPECIFIC_OUTDIR}/cis_eqtl.txt"
    OUTFILE_TRANS="${SPECIFIC_OUTDIR}/trans_eqtl.txt"

    GENOTYPEFILE=${GENO_FMT/\[CHRM\]/${CHRM}}

    MATRIXEQTL_JOBNAME="${THISMETHOD}_${MDATA}_chr${CHRM}_${RANDSTRING}"

    sed -e "s|_JOB_NAME|${MATRIXEQTL_JOBNAME}|g;
            s|_MEQTL_R_|${MATRIXEQTL}|g;
            s|_GT_FILE_|${GENOTYPEFILE}|g;
            s|_SAM_FILE|${SAMPLEFILE}|g;
            s|_EXPR_FL_|${EXPRESSIONFILE}|g;
            s|_GEN_POSF|${GENEPOSFILE}|g;
            s|_MD_TYPE_|${DATATYPE}|g;
            s|_PTHR_CIS|${MEQTL_PVALTHRES_CIS}|g;
            s|_PTHR_TRA|${MEQTL_PVALTHRES_TRANS}|g;
            s|_OUTF_CIS|${OUTFILE_CIS}|g;
            s|_OUTF_TRA|${OUTFILE_TRANS}|g;
            s|_MEQTLMOD|${MATRIXEQTL_MODEL}|g;
            s|_EXT_FLAG|${EXTRAFLAGS}|g;
           " ${MASTER_BSUBDIR}/matrixeqtl.bsub > ${SPECIFIC_JOBSUBDIR}/${MATRIXEQTL_JOBNAME}.bsub

    submit_job ${SPECIFIC_JOBSUBDIR} ${MATRIXEQTL_JOBNAME} ${THISJOBDEPS}
    JOBDEPS=`add_deps "${JOBDEPS}" ${MATRIXEQTL_JOBNAME}`

done
