#!/bin/bash

function submit_tejaas() {
    local pyenv=$1
    local tejaas=$2
    local chrm=$3
    local genotype=$4
    local expression=$5
    local corrected_expression=$6
    local geneinfo=$7
    local maffile=$8
    local method=$9
    local null=${10}
    local snpthres=${11}
    local genethres=${12}
    local sbeta=${13}
    local extraflags=${14}
    local jobsubdir=${15}
    local outdir=${16}
    local jobprefix=${17}
    local nmax=${18}
    local thisjobdep=${19}
    local bsubdir=${20}
    local __jobdeps=${21} ## name of the bash variable
    local jobdeps=${22}   ## contents of the bash variable
    local ntot=${23}
    local jobname=0
    local i=0
    local index=0
    local includesnps=0
    local startsnp=0
    local endsnp=0
    local outprefix=0

    ## echo $tejaas $chrm $genotype ${expression} ${sample} ${geneinfo} $maffile
    ## echo "Method: " ${method} ${null} ${snpthres} ${genethres} ${sbeta}
    ## echo "Extraflags: " ${extraflags}
    ## echo $jobsubdir $outdir $jobprefix
    ## echo $nmax $thisjobdep $bsubdir $__jobdeps $jobdeps

    ## header lines are removeed with the sed construct
    ## ntot=$( zcat ${genotype} | sed '/^\s*#/d;/^\s*$/d' | wc -l )
    njobs=$( echo $(( (ntot + nmax - 1)/nmax )) )

    if [ -d ${jobsubdir} ]; then rm -rf ${jobsubdir}; fi; mkdir -p ${jobsubdir}
    if [ -d ${outdir} ]; then rm -rf ${outdir}; mkdir -p ${outdir}; fi

    for (( i=0; i < ${njobs}; i++ )); do
        index=`echo ${i} | awk '{printf "%03d", $1}'`
        jobname="${jobprefix}_${index}"

        startsnp=$(( nmax * i + 1 ))
        endsnp=$(( nmax * (i + 1) ))
        if [ $endsnp -gt $ntot ]; then
            endsnp=${ntot}
        fi
        includesnps="${startsnp}:${endsnp}"

        outprefix="${outdir}/chunk${index}"

        # create the job submission file
        sed "s|_JOB_NAME|${jobname}|g;
             s|_PYT_ENV_|${pyenv}|g;
             s|_TJS_BINR|${tejaas}|g;
             s|_GT_FILE_|${genotype}|g;
             s|_EXPR_FL_|${expression}|g;
             s|_GX_CRFL_|${corrected_expression}|g;
             s|_GEN_POSF|${geneinfo}|g;
             s|_TJ_METHD|${method}|g;
             s|_NULL_MDL|${null}|g;
             s|_OUT_PRFX|${outprefix}|g;
             s|_STRT_END|${includesnps}|g;
             s|_SNP_CUT_|${snpthres}|g;
             s|_GEN_CUT_|${genethres}|g;
             s|_SIG_BETA|${sbeta}|g;
             s|_CHRM_NUM|${chrm}|g;
             s|_MAF_FILE|${maffile}|g;
             s|_EXT_FLAG|\"${extraflags}\"|g;
            " ${bsubdir}/tejaas.sbatch > ${jobsubdir}/${jobname}.sbatch

        thisjobid=$( submit_job ${jobsubdir} ${jobname} ${thisjobdep} )
        jobdeps=$( add_deps "${jobdeps}" ${thisjobid} )
    done
    eval $__jobdeps="'$jobdeps'"
}
