#!/bin/bash

function submit_tejaas() {
    local pyenv=$1
    local tejaas=$2
    local chrm=$3
    local genotype=$4
    local expression=$5
    local corrected_expression=$6
    local samplefile=$7 
    local geneinfo=$8
    local maffile=$9
    local method=${10}
    local null=${11}
    local snpthres=${12}
    local genethres=${13}
    local sbeta=${14}
    local extraflags=${15}
    local jobsubdir=${16}
    local outdir=${17}
    local jobprefix=${18}
    local nmax=${19}
    local thisjobdep=${20}
    local bsubdir=${21}
    local __jobdeps=${22} ## name of the bash variable
    local jobdeps=${23}   ## contents of the bash variable
    local ntot=${24}
    local jobname=0
    local i=0
    local outprefix=0

    ## echo $tejaas $chrm $genotype ${expression} ${sample} ${geneinfo} $maffile
    ## echo "Method: " ${method} ${null} ${snpthres} ${genethres} ${sbeta}
    ## echo "Extraflags: " ${extraflags}
    ## echo $jobsubdir $outdir $jobprefix
    ## echo $nmax $thisjobdep $bsubdir $__jobdeps $jobdeps

    ## header lines are removeed with the sed construct
    ## ntot=$( zcat ${genotype} | sed '/^\s*#/d;/^\s*$/d' | wc -l )
    njobs=$( echo $(( (ntot + nmax - 1)/nmax )) )
    narr=$(( njobs - 1 ))

    if [ -d ${jobsubdir} ]; then rm -rf ${jobsubdir}; fi; mkdir -p ${jobsubdir}
    if [ -d ${outdir} ]; then rm -rf ${outdir}; mkdir -p ${outdir}; fi

    jobname="${jobprefix}"
    outprefix="${outdir}/chunk"

    # create the job submission file
    sed "s|_JOB_NAME|${jobname}|g;
         s|_PYT_ENV_|${pyenv}|g;
         s|_TJS_BINR|${tejaas}|g;
         s|_GT_FILE_|${genotype}|g;
         s|_EXPR_FL_|${expression}|g;
         s|_GX_CRFL_|${corrected_expression}|g;
         s|_SAMP_FL_|${samplefile}|g;
         s|_GEN_POSF|${geneinfo}|g;
         s|_TJ_METHD|${method}|g;
         s|_NULL_MDL|${null}|g;
         s|_OUT_PRFX|${outprefix}|g;
         s|_NUM_MAX_|${nmax}|g;
         s|_NUM_TOT_|${ntot}|g;
         s|_SNP_CUT_|${snpthres}|g;
         s|_GEN_CUT_|${genethres}|g;
         s|_SIG_BETA|${sbeta}|g;
         s|_CHRM_NUM|${chrm}|g;
         s|_MAF_FILE|${maffile}|g;
         s|_EXT_FLAG|\"${extraflags}\"|g;
        " ${bsubdir}/tejaas.sbatch > ${jobsubdir}/${jobname}.sbatch

    thisjobid=$( submit_job_array ${jobsubdir} ${jobname} ${thisjobdep} ${narr} )
    #thisjobid="999"
    jobdeps=$( add_deps "${jobdeps}" ${thisjobid} )
    eval $__jobdeps="'$jobdeps'"
}
