#!/bin/bash

THISMETHOD="tejaas"
THISJOBDEPS="None"

# source ${UTILSDIR}/submit_tejaas
source ${UTILSDIR}/submit_tejaas_array

EXTRAFLAGS="--dosage --gxcorr ${EXPRCORRFILE}"
_VARIANT=""

if [ "${KNN}" -gt "0" ]; then
    EXTRAFLAGS="$EXTRAFLAGS --knn ${KNN}"
    _VARIANT="${_VARIANT}_knn${KNN}"
fi

if [ "${CISMASK}" == "true" ]; then
    EXTRAFLAGS="$EXTRAFLAGS --cismask"
else
    _VARIANT="${_VARIANT}_nocismask"
fi

if [ "${CROSSMAP}" == "true" ]; then
    EXTRAFLAGS="$EXTRAFLAGS --crossmap ${CROSSMAPFILE}"
    _VARIANT="${_VARIANT}_crossmap"
fi

if [ "${MAGIC_SQRT}" == "true" ]; then
    EXTRAFLAGS="$EXTRAFLAGS --magic_sqrt"
    _VARIANT="${_VARIANT}_sqrt"
fi

if [ "${SHUFFLE_SPECIAL}" == "true" ]; then
    EXTRAFLAGS="$EXTRAFLAGS --shuffle-special"
    _VARIANT="${_VARIANT}_shuf"
fi

if [ "${NOGTKNN}" == "true" ]; then
    EXTRAFLAGS="$EXTRAFLAGS --nogtknn"
    _VARIANT="${_VARIANT}_nogtknn"
fi

if [ "${DATATYPE}" == "cardiogenics" ]; then
    EXTRAFLAGS="$EXTRAFLAGS --trim"
fi

if [ "${DATATYPE}" == "fhs" ]; then
    GENEINFOFILE=${PROBEINFOFILE}
fi

if [ "${SHUFFLE}" == "true" ]; then
    THISMETHOD="tejaas_rand"
    EXTRAFLAGS="$EXTRAFLAGS --shuffle-with $SHUFFLED_ID_FILE"
    SHUFFLE=false
fi

for CHRM in ${CHRNUMS}; do
    # GENOTYPEFILE=${GENO_FMT/\[CHRM\]/${CHRM}}
    GENOTYPEFILE=${GENO_VCF_FMT/\[CHRM\]/${CHRM}}
    # if [ "${DATATYPE}" == "fhs" ]; then
    #     GENOTYPEFILE=${GENO_FMT/\[CHRM\]/${CHRM}}
    # fi
    MAF_1KG_FILE=${MAF_1KG_FMT/\[CHRM\]/${CHRM}}

    CHRM_NTOT_FILE="$( dirname ${GENOTYPEFILE} )/ntot_per_chromosome.txt"
    NTOT_CHRM=$( sed "${CHRM}q;d" ${CHRM_NTOT_FILE} | awk '{print $2}' )

    if [ "${RUNJPA}" = "true" ]; then
        METHOD_VARIANT="jpa"
        if [ "${_VARIANT}" != "" ]; then
            METHOD_VARIANT="${METHOD_VARIANT}${_VARIANT}"
        fi

        SPECIFIC_OUTDIR="${OUTDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
        SPECIFIC_JOBSUBDIR="${JOBSUBDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
        
        JOBPREFIX="${THISMETHOD}_${METHOD_VARIANT}_${TISSUEID}_chr${CHRM}_${RANDSTRING}"

        submit_tejaas ${TEJAAS} ${CHRM} ${GENOTYPEFILE} ${EXPRESSIONFILE} ${SAMPLEFILE} \
                              ${GENEINFOFILE} ${MAF_1KG_FILE} \
                              ${TEJAAS_MODEL} ${NULL} \
                              ${TEJAAS_SNPS_THRES} ${TEJAAS_GENE_THRES} ${SBETA}\
                              "${EXTRAFLAGS}" \
                              ${SPECIFIC_JOBSUBDIR} ${SPECIFIC_OUTDIR} ${JOBPREFIX} \
                              ${MAX_NSNP_PERJOB} \
                              ${THISJOBDEPS} ${MASTER_BSUBDIR} \
                              JOBDEPS "${JOBDEPS}" ${NTOT_CHRM}

    else
        for NULL in ${TEJAAS_NULL}; do
            if [ ${NULL} == "perm" ]; then TEJAAS_SIGMA_BETA=${TEJAAS_SIGMA_BETA_PERM}; fi
            if [ ${NULL} == "maf" ]; then TEJAAS_SIGMA_BETA=${TEJAAS_SIGMA_BETA_MAF}; fi
            if [ ${DYNAMIC_SB} == "true" ]; then
                for KEFF in ${KEFFS}; do
                    METHOD_VARIANT="${NULL}null_sbDynamic${KEFF}"
                    SBETA="0.00"
                    EXTRAFLAGS="$EXTRAFLAGS --dynamic ${KEFF}"
                    if [ "${_VARIANT}" != "" ]; then
                        METHOD_VARIANT="${METHOD_VARIANT}${_VARIANT}"
                    fi

                    SPECIFIC_OUTDIR="${OUTDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
                    SPECIFIC_JOBSUBDIR="${JOBSUBDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"

                    JOBPREFIX="${THISMETHOD}_${METHOD_VARIANT}_${TISSUEID}_chr${CHRM}_${RANDSTRING}"

                    submit_tejaas ${TEJAAS} ${CHRM} ${GENOTYPEFILE} ${EXPRESSIONFILE} ${SAMPLEFILE} \
                                ${GENEINFOFILE} ${MAF_1KG_FILE} \
                                ${TEJAAS_MODEL} ${NULL} \
                                ${TEJAAS_SNPS_THRES} ${TEJAAS_GENE_THRES} ${SBETA}\
                                "${EXTRAFLAGS}" \
                                ${SPECIFIC_JOBSUBDIR} ${SPECIFIC_OUTDIR} ${JOBPREFIX} \
                                ${MAX_NSNP_PERJOB} \
                                ${THISJOBDEPS} ${MASTER_BSUBDIR} \
                                JOBDEPS "${JOBDEPS}" ${NTOT_CHRM}
                done
            elif [ ${MML_OPT} == "true" ]; then
                METHOD_VARIANT="${NULL}null_sbMMLopt"
                SBETA="0.00"
                EXTRAFLAGS="$EXTRAFLAGS --mml"
                if [ "${_VARIANT}" != "" ]; then
                    METHOD_VARIANT="${METHOD_VARIANT}${_VARIANT}"
                fi

                SPECIFIC_OUTDIR="${OUTDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
                SPECIFIC_JOBSUBDIR="${JOBSUBDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"

                JOBPREFIX="${THISMETHOD}_${METHOD_VARIANT}_${TISSUEID}_chr${CHRM}_${RANDSTRING}"

                submit_tejaas ${TEJAAS} ${CHRM} ${GENOTYPEFILE} ${EXPRESSIONFILE} ${SAMPLEFILE} \
                            ${GENEINFOFILE} ${MAF_1KG_FILE} \
                            ${TEJAAS_MODEL} ${NULL} \
                            ${TEJAAS_SNPS_THRES} ${TEJAAS_GENE_THRES} ${SBETA}\
                            "${EXTRAFLAGS}" \
                            ${SPECIFIC_JOBSUBDIR} ${SPECIFIC_OUTDIR} ${JOBPREFIX} \
                            ${MAX_NSNP_PERJOB} \
                            ${THISJOBDEPS} ${MASTER_BSUBDIR} \
                            JOBDEPS "${JOBDEPS}" ${NTOT_CHRM}
            else
                for SBETA in ${TEJAAS_SIGMA_BETA}; do
                    METHOD_VARIANT="${NULL}null_sb${SBETA}"
                    if [ "${_VARIANT}" != "" ]; then
                        METHOD_VARIANT="${METHOD_VARIANT}${_VARIANT}"
                    fi

                    SPECIFIC_OUTDIR="${OUTDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
                    SPECIFIC_JOBSUBDIR="${JOBSUBDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
        
                    JOBPREFIX="${THISMETHOD}_${METHOD_VARIANT}_${TISSUEID}_chr${CHRM}_${RANDSTRING}"
        
                    submit_tejaas ${TEJAAS} ${CHRM} ${GENOTYPEFILE} ${EXPRESSIONFILE} ${SAMPLEFILE} \
                                  ${GENEINFOFILE} ${MAF_1KG_FILE} \
                                  ${TEJAAS_MODEL} ${NULL} \
                                  ${TEJAAS_SNPS_THRES} ${TEJAAS_GENE_THRES} ${SBETA}\
                                  "${EXTRAFLAGS}" \
                                  ${SPECIFIC_JOBSUBDIR} ${SPECIFIC_OUTDIR} ${JOBPREFIX} \
                                  ${MAX_NSNP_PERJOB} \
                                  ${THISJOBDEPS} ${MASTER_BSUBDIR} \
                                  JOBDEPS "${JOBDEPS}" ${NTOT_CHRM}
                done
            fi
        done

    fi
done

RUNJPA=false
