#!/bin/bash

function tejaas_top_snps() {
    local DIR=$1
    local CWD=`pwd`
    local CUT=$2
    # cd $DIR
    echo $DIR
    $PYENV $SCRIPTDIR/select_top_rr.py --indir $DIR --outdir $DIR --c $CUT
    # cd $CWD
}
