#!/bin/bash

THISMETHOD="tejaas"
THISJOBDEPS="None"

echo "Submitting TEJAAS jobs with RUNJPA=$RUNJPA and SHUFFLE=$SHUFFLE"
source ${UTILSDIR}/submit_tejaas

EXTRAFLAGS="--dosage"
if [ "${DATATYPE}" = "cardiogenics" ]; then
    EXTRAFLAGS="$EXTRAFLAGS --trim"
fi

if [ "${SHUFFLE}" = "true" ]; then
    THISMETHOD="tejaas_rand"
    EXTRAFLAGS="$EXTRAFLAGS --trim --shuffle"
    SHUFFLE=false
fi


for CHRM in ${CHRNUMS}; do
    GENOTYPEFILE=${GENO_FMT/\[CHRM\]/${CHRM}}
    MAF_1KG_FILE=${MAF_1KG_FMT/\[CHRM\]/${CHRM}}

    if [ "${RUNJPA}" = "true" ]; then
        METHOD_VARIANT="jpa"
        SPECIFIC_JOBSUBDIR="${JOBSUBDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
        SPECIFIC_OUTDIR="${OUTDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"

        JOBPREFIX="${THISMETHOD}_${METHOD_VARIANT}_${MDATA}_chr${CHRM}_${RANDSTRING}"

        submit_tejaas ${TEJAAS} ${CHRM} ${GENOTYPEFILE} ${EXPRESSIONFILE} ${SAMPLEFILE} \
                      ${GENEINFOFILE} ${MAF_1KG_FILE} \
                      jpa perm \
                      ${TEJAAS_SNPS_THRES} ${TEJAAS_GENE_THRES} 0.01 \
                      "${EXTRAFLAGS}" \
                      ${SPECIFIC_JOBSUBDIR} ${SPECIFIC_OUTDIR} ${JOBPREFIX} \
                      ${MAX_NSNP_PERJOB} \
                      ${THISJOBDEPS} ${MASTER_BSUBDIR} \
                      JOBDEPS "${JOBDEPS}"

    else
        for NULL in ${TEJAAS_NULL}; do
            for SBETA in ${TEJAAS_SIGMA_BETA}; do
    
                METHOD_VARIANT="${NULL}null_sb${SBETA}"
                SPECIFIC_JOBSUBDIR="${JOBSUBDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
                SPECIFIC_OUTDIR="${OUTDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
    
                JOBPREFIX="${THISMETHOD}_${METHOD_VARIANT}_${MDATA}_chr${CHRM}_${RANDSTRING}"
    
                submit_tejaas ${TEJAAS} ${CHRM} ${GENOTYPEFILE} ${EXPRESSIONFILE} ${SAMPLEFILE} \
                              ${GENEINFOFILE} ${MAF_1KG_FILE} \
                              ${TEJAAS_MODEL} ${NULL} \
                              ${TEJAAS_SNPS_THRES} ${TEJAAS_GENE_THRES} ${SBETA}\
                              "${EXTRAFLAGS}" \
                              ${SPECIFIC_JOBSUBDIR} ${SPECIFIC_OUTDIR} ${JOBPREFIX} \
                              ${MAX_NSNP_PERJOB} \
                              ${THISJOBDEPS} ${MASTER_BSUBDIR} \
                              JOBDEPS "${JOBDEPS}"
    
            done
        done

    fi
done

RUNJPA=false
