#!/bin/bash

THISMETHOD="tejaas"
THISJOBDEPS="None"

echo "Submitting TEJAAS jobs with RUNJPA=$RUNJPA and SHUFFLE=$SHUFFLE"
source ${UTILSDIR}/submit_tejaas


if [ "${DATATYPE}" = "cardiogenics" ]; then
    EXTRAFLAGS="$EXTRAFLAGS --trim"
fi

for it in `seq 1 44`; do

  EXTRAFLAGS="--dosage --cismask --shuffle"
  THISMETHOD="tejaas_rand_${it}"

  for CHRM in ${CHRNUMS}; do
      GENOTYPEFILE=${GENO_FMT/\[CHRM\]/${CHRM}}
      MAF_1KG_FILE=${MAF_1KG_FMT/\[CHRM\]/${CHRM}}

      if [ "${RUNJPA}" = "true" ]; then
          METHOD_VARIANT="jpa"
          if [ "${bTejaasPartition}" = "true" ]; then
              SPECIFIC_OUTDIR="${OUTDIR_DATA}/${r}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
              SPECIFIC_JOBSUBDIR="${JOBSUBDIR_DATA}/${r}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
          else
              SPECIFIC_OUTDIR="${OUTDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
              SPECIFIC_JOBSUBDIR="${JOBSUBDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
          fi

          JOBPREFIX="${THISMETHOD}_${METHOD_VARIANT}_${MDATA}_chr${CHRM}_${RANDSTRING}"

          submit_tejaas ${TEJAAS} ${CHRM} ${GENOTYPEFILE} ${EXPRESSIONFILE} ${SAMPLEFILE} \
                        ${GENEINFOFILE} ${MAF_1KG_FILE} \
                        jpa perm \
                        ${TEJAAS_SNPS_THRES} ${TEJAAS_GENE_THRES} 0.01 \
                        "${EXTRAFLAGS}" \
                        ${SPECIFIC_JOBSUBDIR} ${SPECIFIC_OUTDIR} ${JOBPREFIX} \
                        ${MAX_NSNP_PERJOB} \
                        ${THISJOBDEPS} ${MASTER_BSUBDIR} \
                        JOBDEPS "${JOBDEPS}"

      else
          for NULL in ${TEJAAS_NULL}; do
              if [ ${NULL} == "perm" ]; then TEJAAS_SIGMA_BETA=${TEJAAS_SIGMA_BETA_PERM}; fi
              if [ ${NULL} == "maf" ]; then TEJAAS_SIGMA_BETA=${TEJAAS_SIGMA_BETA_MAF}; fi
              for SBETA in ${TEJAAS_SIGMA_BETA}; do
                  METHOD_VARIANT="${NULL}null_sb${SBETA}"
                  if [ "${bTejaasPartition}" = "true" ]; then
                      SPECIFIC_OUTDIR="${OUTDIR_DATA}/${r}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
                      SPECIFIC_JOBSUBDIR="${JOBSUBDIR_DATA}/${r}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
                  else
                      SPECIFIC_OUTDIR="${OUTDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
                      SPECIFIC_JOBSUBDIR="${JOBSUBDIR_DATA}/${THISMETHOD}/${METHOD_VARIANT}/chr${CHRM}"
                  fi
      
                  JOBPREFIX="${THISMETHOD}_${METHOD_VARIANT}_${MDATA}_chr${CHRM}_${RANDSTRING}"
      
                  submit_tejaas ${TEJAAS} ${CHRM} ${GENOTYPEFILE} ${EXPRESSIONFILE} ${SAMPLEFILE} \
                                ${GENEINFOFILE} ${MAF_1KG_FILE} \
                                ${TEJAAS_MODEL} ${NULL} \
                                ${TEJAAS_SNPS_THRES} ${TEJAAS_GENE_THRES} ${SBETA}\
                                "${EXTRAFLAGS}" \
                                ${SPECIFIC_JOBSUBDIR} ${SPECIFIC_OUTDIR} ${JOBPREFIX} \
                                ${MAX_NSNP_PERJOB} \
                                ${THISJOBDEPS} ${MASTER_BSUBDIR} \
                                JOBDEPS "${JOBDEPS}"
      
              done
          done

      fi
  done
done

RUNJPA=false
