#!/bin/bash
function abs_path() {
    # $1: relative path
    echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}

# a beautiful one-line to get the full directory name of the location of this script
CURDIRUP="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Pipeline directories
UTILSDIR=$(abs_path "${CURDIRUP}/utils")
CONFIGDIR=$(abs_path "${CURDIRUP}/configs")
SCRIPTDIR=$(abs_path "${CURDIRUP}/../scripts")
MASTER_BSUBDIR=$(abs_path "${CURDIRUP}/../bsubfiles")
JOBSUBDIR=$(abs_path "${CURDIRUP}/../jobsubs")
ANALYSISDIR=$(abs_path "${CURDIRUP}/../analysis")
PREPROCDIR=$(abs_path "${CURDIRUP}/../preprocess")

# Script files
MATRIXEQTL=$(abs_path "${SCRIPTDIR}/matrixeqtl.R")
SBOPT_PY=$(abs_path "${SCRIPTDIR}/sigbeta_optimizer.py")
LDPRUNE_PY=$(abs_path "${SCRIPTDIR}/prune_ld_snps.py")
