#!/bin/bash

CURDIR=`pwd`

# data directory
DATADIR="/scratch/sbanerj/data"
GENEPOSFILE="${DATADIR}/GENCODE/genepos.gencode.v19.txt"

# output directory
OUTDIR="/scratch/sbanerj/trans-eqtl/dev-pipeline"

# Cardiogenics
CARDIODIR="${DATADIR}/Cardiogenics"
CARDIO_EXPR_FMT="${CARDIODIR}/expression/cardio_[TISSUE]_expr_gencode_filter.txt"
CARDIO_GENO_FMT="${CARDIODIR}/genotype_qc/CG_dosages_filtered_[CHRM].imputed.gz"
CARDIO_BGEN_FMT="${CARDIODIR}/genotype_qc/CG_filtered_imputed_[CHRM].bgen"
CARDIO_SAMPLE="${CARDIODIR}/genotype_qc/CG.sample"

# GTEx
GTEXDIR="${DATADIR}/GTEx"
GTEX_EXPR_FMT="${GTEXDIR}/expression/gtex.normalized.expression.lmcorrected.[TISSUE].txt"
GTEX_GENO_FMT="${GTEXDIR}/genotype_qc/dosages/GTEx_Analysis_20150112_OMNI_2.5M_5M_450Indiv_genot_imput_info04_maf01_HWEp1E6_ConstrVarIDs_dosages_chr[CHRM].gz"
GTEX_SAMPLE="${GTEXDIR}/gtex.sample"

# 
DATATYPE=`echo ${MDATA} | cut -d'-' -f1`
TISSUEID=`echo ${MDATA} | cut -d'-' -f2`
case "${DATATYPE}" in  # adding new dataset is easier with case than with if-else
    "cardio")
        DATATYPE="cardiogenics" # renaming data type from input
        EXPRESSIONFILE=${CARDIO_EXPR_FMT/\[TISSUE\]/${TISSUEID}}
        GENO_FMT=${CARDIO_GENO_FMT}
        SAMPLEFILE=${CARDIO_SAMPLE}
        ;;
    "gtex")
        DATATYPE="gtex"
        EXPRESSIONFILE=${GTEX_EXPR_FMT/\[TISSUE\]/${TISSUEID}}
        GENO_FMT=${GTEX_GENO_FMT}
        SAMPLEFILE=${GTEX_SAMPLE}
        ;;
    *)
        EXPRESSIONFILE=""
        GENO_FMT=""
        SAMPLEFILE=""
        ;;
esac

# Pipeline directories
UTILSDIR="${CURDIR}/utils"
CONFIGDIR="${CURDIR}/configs"
SCRIPTDIR="${CURDIR}/../scripts"
MASTER_BSUBDIR="${CURDIR}/../bsubfiles"
JOBSUBDIR="${CURDIR}/../jobsubs"
ANALYSISDIR="${CURDIR}/../analysis"

# Script files
MATRIXEQTL="${SCRIPTDIR}/matrixeqtl.R"

# external programs required for the pipeline
LDSTORE="${HOME}/packages/ldstore/ldstore_v1.1_x86_64/ldstore"
