#!/bin/bash

DATALOAD="DATA.SAIKAT"
DATASET="GTEx"
#CHRNUMS="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22"
CHRNUMS="1 2 3 4 5 6"
#CHRNUMS="22"
GXNPEER="0"
GXSELECTION="protein_coding"

# MatrixEQTL options
bMatrixEqtl=false			# run the method if true
bMEqtlRandom=false			# run the method if true
AGE_CORRECTION="true"
MEQTL_PVALTHRES_CIS=0.001
MEQTL_PVALTHRES_TRANS=0.001
MATRIXEQTL_MODEL="modelLINEAR"

# TEJAAS options
bTejaas=true				# run the method if true
bTjsRandom=true
TEJAAS_MODEL="jpa-rr" 			# only one model allowed
TEJAAS_NULL="perm" 			# list of null models
TEJAAS_SIGMA_BETA_PERM="0.05"           # list of sigma beta for perm null
TEJAAS_SIGMA_BETA_MAF="0.001" 		# list of sigma beta for MAF null
MAX_NSNP_PERJOB=20000 			# number of SNPs for analysis by TEJAAS per job
TEJAAS_SNPS_THRES=0.001 		# all trans-eQTLs are printed, but target genes are printed for those trans-eQTLs below this threshold
TEJAAS_GENE_THRES=0.001 		# even for the above, not all target genes are printed; only those with p-values below this threshold

# CPMA options
bTejaasJPA=false
bJPARandom=false
GNLMM_SNP_PER_JOB=20000


# GNetLMM options
bGNetLmm=false
bGNLRandom=false

# Which methods to run?
bValidationPlot=false
