#!/bin/bash

extract_selected_samples_tpm_counts() {
    SRCTPM=$1
    SRCREAD=$2
    SEL_SAMPLES=$3
    ALL_SAMPLES=$4
    TPMOUT=$5
    COUNTOUT=$6
    TMP_OUTDIR=$( dirname $TPMOUT )

    grep -n -Fwf ${SEL_SAMPLES} ${ALL_SAMPLES} | cut -d':' -f1 > ${TMP_OUTDIR}/tmp.columns
    TRGTFIELDS="1,2,$(tr '\n' ',' < ${TMP_OUTDIR}/tmp.columns)"
    TRGTFIELDS=${TRGTFIELDS::-1}
    zcat ${SRCTPM} | head -n 2  > ${TPMOUT}
    zcat ${SRCREAD} | head -n 2  > ${COUNTOUT}
    zcat ${SRCTPM} | tail -n +3 | cut -f$TRGTFIELDS >> ${TPMOUT}
    zcat ${SRCREAD} | tail -n +3 | cut -f$TRGTFIELDS >> ${COUNTOUT}
    rm -f ${TMP_OUTDIR}/tmp.columns
}
