#!/bin/bash

TISSUEFILE="tissue_table.txt"
DATALOAD="configs/GTEXv8.SAIKAT"
EXTERNALLOAD="configs/EXTERNAL.SAIKAT"
OUTDIR="/scratch/sbanerj/trans-eqtl/input/gtex_v8"

GXOUTDIR="${OUTDIR}/expression"
GTOUTDIR="${OUTDIR}/genotype"
PREGXOUTDIR="${OUTDIR}/preprocess_gx"
COVARDIR="${OUTDIR}/covariates"

#---- Gene expression meta data
# GENEPOSFILE="${GXOUTDIR}/genepos.gencode.v19.txt"

#---- Options for gene expression pre-filtering
USE_SLURM=true
USE_LSF=false
GXSELECTION="protein_coding lncRNA"   # a list of biotypes to be selected for analysis
QCMETHODS="raw raw_std raw_cclm_std raw_cclasso_std"
TPM_THRESHOLD=0.1
COUNTS_THRESHOLD=6
SAMPLE_FRAC_THRESHOLD=0.2
bCollectCovs=true
bSelectTissue=true
bNormalizeQC=true

#---- Genotype filtering
MAFMIN=0.01
REMOVE_INDELS=true
REMOVE_AMBIGUOUS=true
IMPUTE_MISSING=true

#---- GNetLMM format
CREATE_EXPRESSION=false
CREATE_GENOTYPE=true

for DIR in ${GXOUTDIR} ${GTOUTDIR} ${PREGXOUTDIR} ${COVARDIR}; do
    if [ ! -d ${DIR} ]; then mkdir -p $DIR; fi
done

## #---- use Age correction? 
## CORRECT_AGE=true

## #---- PEER config
## NCOVS="0 1 5 10 15 20"

### from within R (for lm correction script)
# install.packages("argparser")
#### PEER Instalation
# wget https://github.com/downloads/PMBio/peer/R_peer_source_1.3.tgz
# R CMD INSTALL R_peer_source_1.3.tgz
