#!/bin/bash

TISSUEFILE="tissue_table.txt"
DATALOAD="configs/DATA.SAIKAT"
EXTERNALLOAD="configs/EXTERNAL.SAIKAT"
OUTDIR="/scratch/sbanerj/trans-eqtl/input/gtex"


GXOUTDIR="${OUTDIR}/expression"
GTOUTDIR="${OUTDIR}/genotype"
PREGXOUTDIR="${OUTDIR}/preprocess_gx"

RPKMOUTDIR="${PREGXOUTDIR}/rpkms"                  # tissue specific rpkms output dir
NORMOUTDIR="${PREGXOUTDIR}/normalized"             # normalized, uncorrected expr dir
LMOUTDIR="${PREGXOUTDIR}/lmcorrected"              # covariate corrected expression
COVOUTDIR="${PREGXOUTDIR}/covariates"              # covariates outdir
PEEROUTDIR="${PREGXOUTDIR}/peercorrected"          # PEER corrected
AGE_COVARIATE_FILE="${COVOUTDIR}/gtex_age_covariate.txt"  # where to store the age covariate


GXFILENAME_FMT="${GXOUTDIR}/gtex_[SELECTION]_[PREPROC]_[TISSUE].txt"
GTFILE_BASENAME="GTEx_v6_imput_info04_HWEp1E6_PASS_dbSNP135"

#---- Gene expression meta data
GENEPOSFILE="${GXOUTDIR}/genepos.gencode.v19.txt"

#---- Different types of gene expression preprocessing
USE_BSUB=false
GXSELECTION="protein_coding"   # a list of biotypes to be selected for analysis
bSelectNormalize=false
bFormatCovariates=false
bLMcorrect=false
bPeerCorrect=false
bGencodeFilter=true
GXAGECORR="false"               # a list of boolean, "true false", true: gx will be corrected for age
GXNPEERS="35"                   # number of peer factors, redundant if bPeerCorrect = false

#---- Genotype filtering
MAFMIN=0.1
REMOVE_INDELS=true
REMOVE_AMBIGUOUS=true
IMPUTE_MISSING=true

#---- GNetLMM format
CREATE_EXPRESSION=false
CREATE_GENOTYPE=true

## #---- Gene Expression processing
## bProcessRPKMs_and_normalize=false    # start from the very beginning
## bformatCovariates=false              # format the covariates file
## bLMcorrect=false                     # use covariate file to correct gx with Linear Model
## GTEX_PEER_CORRECTION=false           # apply PEER correction to GTEx gx
## GENCODE_FILTER=true


## #---- use Age correction? 
## CORRECT_AGE=true

## #---- PEER config
## NCOVS="0 1 5 10 15 20"

### from within R (for lm correction script)
# install.packages("argparser")
#### PEER Instalation
# wget https://github.com/downloads/PMBio/peer/R_peer_source_1.3.tgz
# R CMD INSTALL R_peer_source_1.3.tgz
