#!/bin/bash

SRCDIR="/scratch/sbanerj/data/GTEx/v6"

SRCVCF="${SRCDIR}/genotype/GTEx_Analysis_20150112_OMNI_2.5M_5M_450Indiv_chr1to22_genot_imput_info04_maf01_HWEp1E6_ConstrVarIDs.vcf.gz"
SRCLOOKUP="${SRCDIR}/genotype/GTEx_Analysis_2015-01-12_OMNI_2.5M_5M_450Indiv_chr1to22_phased_genot_imput_info04_maf01_HWEp1E6_VarID_Lookup_Table.txt.gz"

SRCRPKM="${SRCDIR}/expression/GTEx_Data_20150112_RNAseq_RNASeQCv1.1.8_gene_rpkm.gct.gz"
SRCREAD="${SRCDIR}/expression/GTEx_Data_20150112_RNAseq_RNASeQCv1.1.8_gene_reads.gct.gz"

SRCPHENO="${SRCDIR}/phenotype/phs000424.v6.pht002743.v6.p1.c1.GTEx_Sample_Attributes.GRU.txt"
