#!/bin/bash

VCFTOOLS="/usr/users/sbanerj/packages/vcftools/vcftools-v0.1.15/bin/vcftools"
BGZIP="/usr/users/sbanerj/packages/htslib/htslib-1.4.1/bin/bgzip"
TABIX="/usr/users/sbanerj/packages/htslib/htslib-1.4.1/bin/tabix"
PLINK2="/usr/users/fsimone/bin/plink2"
PYENV="/usr/users/fsimone/opt/miniconda/3/envs/env3.6/bin/python"
